### ISSUE TITLE
Improved Quick Search endpoint

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#15]
# Context
The [first pass](https://github.com/Police-Data-Accessibility-Project/data-sources-mirror/issues/13) uses `county_name` and `name`. This is a refinement, checking the user-entered string for matches on several columns.

## Description
"What are you looking for?"

Properties searched | Notes
--- | ---
`name` | from the data sources table
`record_type` |
`description` | 
`tags` | this might be all tags are good for

## Location
"From where?"

Properties searched | Notes
--- | --- 
`agency_described` |
`agency.state` |
`agency.county` |
`agency.municipality` |
`agency.agency_type` |
`agency.jurisdiction_type` |

# Example queries
- Location: `pennsylvania` `PA` `allegheny county` `pittsburgh, PA` `philadelphia` `pittsburgh and philadelphia`
- Description: `complaints` `traffic stops` `officer records` `surveillance` `accidents` `clearance rates`

**Comment by kalenluciano** [comment]
The current quick search endpoint seems to be selecting all entries in the agency_source_link table, maxing out at 1000 rows (because Supabase defaults to maxing out a query at 1000 rows), and nullifying all data_sources and agencies that don't match the search and county parameters. If this is the case, the query might be missing data_sources/agencies matches past the 1000th row in the agency_source_link table. 

Possible solutions to explore:
- Switch to a psycopg2 package or similar to use raw SQL (similar to what we might have to do for the more complicated queries that we're trying to use here to improve the quick search endpoint)
- Explore if there's a way to remove the data_sources and agencies that are getting nullified in Supabase to prevent from hitting the 1000 row cap and returning before it searches through the entire agency_source_link table
- Bypass the default 1000 row max on Supabase (though this will probably slow things down, especially as the database scales)

Re: an autcomplete/smart search, I've used the Google Maps autocomplete before to basically help catch user errors (for example, if they meant to type in "Allegheny, PA" but instead typed "Allgheny, PA", the autocomplete would essentially find the closest match being "Allegheny, PA" and use that as the county/location parameter in the API query). We could consider using something like that if that addresses the kind of "magic" you're trying to get at Josh.

**Comment by josh-chamberlain** [comment]
@kalenluciano re: the final point, that sounds good—I think you understand the goal of giving the user some freedom to type the location they're after and do our best to narrow it down / help them without being too picky. I'm sure we aren't the first to try to figure that out. 

I will leave choosing from the other solutions to @mbodeantor

**Comment by kalenluciano** [comment]
I did as you suggested @mbodeantor, adding wildcards and "like" for querying. I also addressed Josh's [new issue](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/45) real quick as well. Let me know what you think
