### ISSUE TITLE
Permissions for users

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#162]
Follows #24
Part of #318 

# Context

We need to give our users permissions to do things in certain circumstances.

Examples:
- make edits to a data source and submit them for review
- "follow" data sources or searches for updates
- manage user profile
- manage requests
- modify and submit changes for data sources, agencies, etc
  - review changes by others

## Roles & permissions

- We’ll use "attributes" which might include "user roles" to set permissions. We will likely need more fine-grained permissions later on, and it's TBD whether we'll flesh out roles or do it another way. Whatever we call it is fine as long as we're consistent!

# Requirements

- [ ] set up architecture for permissions 
- [ ] develop a CRUD endpoint for managing permissions (an admin task at first, with potential tooling around it)

# Test Cases

- [ ] Confirm that users cannot update the password of a *different* user using their own api key

**Comment by maxachis** [comment]
@josh-chamberlain From my vantage point, this has several components:

* Creating a new table in the database called `permissions` which details the given permissions and their permission_ids
* Creating a linking table `user_permissions`, which associates users with permissions, in a many-to-many relationship. 
* Modifying select endpoints to be able to retrieve the permissions for a given user and use that to determine whether this user has the requisite permissions for this endpoint.

**Comment by josh-chamberlain** [comment]
@maxachis that sounds good to me! 

One thing to note that you may already be considering: In addition to giving sets of users permissions, we will also check other attributes—for example, when we check to see if someone can `edit a request`, we should check to see if they are the creator of that request. In general, we will probably show different things to people who `created` or `follow` a given resource.

I think we could accomplish this by either adjusting endpoints to check permissions in addition to other attributes like ownership, or we could also maybe extend the permissions table to check for those kinds of attributes.

**Comment by maxachis** [comment]
@josh-chamberlain So after doing some more thinking on this, I've developed some additional thoughts.

While reading all this, bear in mind that my experience in this domain is quite limited, so I welcome feedback. 

Part of my challenge in thinking about this is determining to what degree these different permissions should be encompassed within a singular system or managed by multiple smaller systems. 

For some of these, the permissions are probably implicit – we probably want to allow each user to be able to manage only their own user profile, and nobody else’s – so I’m not sure we need to incorporate those into an explicit permission granting structure. In such cases, we likely need only to check that the user has the appropriate authentication. 

Users following data sources is not, as far as I can tell, a _permissions_ issue – they can’t be said to own that data source. That's more akin to subscriptions. So that may benefit from a separate system.
* On the other hand, if users can _create and own_ data sources, that would probably fall under the banner of owner-based permissions. But even still, I think that would be separate from merely being able to follow them. 

On the other hand, requests and changes are objects that users can create and where we expect they would want exclusive edit permissions to them, or potentially to grant those permissions to others.  

My thinking is that these three cases: user profiles, following data sources, and managing requests/changes benefit from three separate approaches, rather than a unified system. So breaking apart this issue into separate issues for each may be warranted.

**Comment by josh-chamberlain** [comment]
@maxachis true, a `follow` is not a `permissions` issue.

> For some of these, the permissions are probably implicit – we probably want to allow each user to be able to manage only their own user profile, and nobody else’s – so I’m not sure we need to incorporate those into an explicit permission granting structure. In such cases, we likely need only to check that the user has the appropriate authentication.

What are permissions, if not checking that the user has the appropriate attributes like authentication? But I think I get your point: we return the object's owner on the endpoint, and matching that against the logged-in user dynamically...yeah, that sounds easy and makes sense.

In that case, the permissions table is very simple and just a framework. We could give some specific permissions just to admins.


### GPT dreamings:

```
CREATE TABLE permissions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
);
```

You could also add other props to the permissions table, like `requires_role = "admin"` or `resource_type = "requests"`

Adding some data:

```
INSERT INTO permissions (name) VALUES ('view_public_pages');
INSERT INTO permissions (name) VALUES ('log_in');
INSERT INTO permissions (name) VALUES ('create_requests');
INSERT INTO permissions (name) VALUES ('edit_requests');
INSERT INTO permissions (name) VALUES ('update_profile');
INSERT INTO permissions (name) VALUES ('admin_edit');
```

Linking users to permissions: 

```
CREATE TABLE user_permissions (
    user_id INTEGER REFERENCES users(id),
    permission_id INTEGER REFERENCES permissions(id),
    PRIMARY KEY (user_id, permission_id)
);
```
