### ISSUE TITLE
State Aggregated entries in Agencies - What are they?

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#234]
I'd like clarification on entries in the AGENCIES table which follow the "[State] Aggregated" pattern. These also have the agency_type of "aggregated". Are these referring to state police agencies, or something else?

**Comment by josh-chamberlain** [comment]
I didn't get a notification for this, sorry! If you wanted a quicker answer, feel free to @ me or use Discord. Anyway:


This is a total hack because we don't have a clean way to classify data sources which would have many `agency_described`. Utterly random example, **municipal statistics for all 140 Allegheny County agencies**.

You would have to allow for one or more one or more counties in one or more states, or one or more municipalities...There would be false positives—I could imagine a source covering half the agencies in PA. You want that to be bearable to submit without a ton of data entry (these sources are more often human-maintained), and they should show up in the relevant search.

The ultimate goal: if PDAP tells people they're looking at records about Pittsburgh, we should show them sources which include agencies in Pittsburgh. Right now, I'm pretty sure we don't. We should err on the side of including too many sources, rather than risk not showing someone something that could be useful. i.e. if you search in Pittsburgh we could have a set of search results labeled "Allegheny County sources which may be related:" or "Pennsylvania..." so the expectation is set that it might not be useful.

Some options I've thought about:

1. allow a data source to have many, many `agency_described` and give people a way to enter a list or select them all somehow. This is simplest in a way, but I do not love this option 
2. allow a data source to have a `geography_described` property, used when a source describes multiple agencies. I think most sensible is allowing any combination of munis, counties, and states. For the user experience, they could select multiple munis, or just "multiple agencies in `county`" or "multiple agencies in `state` (multiple states would be OK)".
3. sources have an `agency_aggregation` property, `local` `county` `state` `federal`. If one of those is submitted, it could be required (by the API) that an `aggregation_geo` is submitted with the relevant counties or states.
4. other options abound

**Comment by maxachis** [comment]
@josh-chamberlain Here is one possible solution I'd like your thought on:

I am envisioning two tables:
1.	Establishes the hierarchical relationship between different geographic entities (municipality-county-state, for example)
a.	Each row establishes a single hierarchical relation (e.g., “X is a municipality of COUNTY”, “Y is a county of STATE”, “Z is a local department within MUNICIPALITY).
2.	Relates a specific data source with one or more entities in table 1, and by extension, all children of that table 1 entity. 
a.	Each row establishes a specific entity encompassed by that data source, (e.g. “Data Source Q has information about all MUNICIPAL-level agencies in COUNTY”)
b.	For more unconventional geographic designators (for example, a data source which includes information about some counties in PA and some in Ohio), each row would specify the specific data sources.  

Even if we accept this general idea, this would probably need to be workshopped, because relationships can be complex. The simplest solution, but also the most data-intensive, would be using only Table 1 and manually specifying every single agency encompassed by a data source. Table 2 adds more complex logic, but would remove the need to add as many individual data entries because we could, when necessary, simply specify the parent entity.

**Comment by josh-chamberlain** [comment]
@maxachis thanks for thinking on this. I'm less worried about absolute accuracy than ease of selection.

- non-aggregated sources describe:
   - one agency with one geographic jurisdiction
- aggregated sources describe agencies in:
   - one muni (rare)
   - a few `selected munis`
   - many munis in a `selected county`
   - many munis across multiple counties in a `selected state`
   - munis or counties across multiple state

↑ we don't need to be perfect when we categorize these, we just need enough information to show them in searches for those munis, counties, and states.

your ideas seem to be good ways of _fully_ describing hierarchy, but I'm not sure that level of fidelity is required:

1. the agencies table already does this, right? Any muni-level agency will also have a parent county and state. We don't bother to define hierarchical relationship in advance because if there's ever an agency which needs to make use of it, the geographic hierarchy is included in the definition. 
2. this is sort of how the current data sources table works, but instead of an agency, we'd be linking to a hierarchical relationship. 

 What do you think about my options 2 and 3 above?

**Comment by maxachis** [comment]
@josh-chamberlain 

Of the two options, I think 2 makes the most sense. The main challenge is when a user selects multiple states: how do we represent that information in the database? While "multiple agencies in COUNTY" and "multiple counties in STATE" would work, "multiple states" would mean they'd show up on virtually every search.

A concatenated string of all states would be unwieldy and hard to search on. A linking table which associates a state-aggregated data source with all relevant states via the `states` table, would probably work better. To find all state-aggregated sources containing a specific state, one would simply need to search for that state in the linking table.

### Side Note

How do we deal with misspellings or inconsistent capitalization in searches and data entry? “e.g., “Pittsburgh”, "pittsburgh", “Pitsburgh”, “Pittsburgh city”)

**Comment by josh-chamberlain** [comment]
@maxachis after sleeping on it, I could definitely see a table of links being helpful/needed—but I would really only want to add them for `aggregated` sources, unless that was a bad idea for some reason. for the `multiple states` example, they'd still pick two or more states like `OH` and `PA`. For those aggregated sources which show up in many searches, it would be part of the front end logic to display `aggregated` sources matching a search in a hierarchy that makes sense, which I am confident we can do—a human-aggregated / compiled source is more likely to be useful.

side note: we will probably want to use an existing `semantic search` library / strategy. We already ignore case and do some of this manually—searches for "allegheny county" will reveal "county = Allegheny" but I'm sure we can get better at it. See https://www.atlasobscura.com/, where searching for "pittsburgh" takes you to a dedicated homepage for "[Pittsburgh, Pennsylvania](https://www.atlasobscura.com/things-to-do/pittsburgh-pennsylvania)"

**Comment by maxachis** [comment]
@josh-chamberlain I see two options, one which meets your desire for only having a linking table for aggregated sources, and one which callously disregards that 🔥😈🔥:

1. Modify `agency_described` in `data_sources` to refer either to a single other agency *OR* to a id in a newly-created `source_agency` table. That id can then have multiple rows associating that data source with each relevant agency. Means less content for the linking table, but does mean that searches, inserts, and updates now have to use more complicated conditional logic depending on whether `agency_described` refers to a data source directly or to an entry in the linking table. This would also raise the risk of data integrity issues and potentially be harder to modify if we have to do future changes.
2. Get rid of the `agency_described` column completely and have the `source_agency` table describe _all_ connections between data sources and agencies, regardless of whether they are aggregated or not. This means that more data is in the `source-agency` table, but it simplifies the design of `data_sources` as well as the logic (which will also make maintenance and updates easier). To convert from the current form to the new form would mean require only a script to perform the transformation, and the frontend could still portray the agencies and data sources as unified.

Option 2 is more aligned with best practice for database design and normalization, and hence is my preference. It also does not have to be the form that users see and modify the data -- they can have a view/web UI which portrays the data in a more user-friendly format. 

side note: In that case, [Elasticsearch ](https://www.elastic.co/)would probably be a good solution to consider. A cursory google search suggest there are ways to [pipeline PostgreSQL databases](https://www.elastic.co/guide/en/enterprise-search/current/postgresql-connector-client-tutorial.html) into that.

**Comment by josh-chamberlain** [comment]
@maxachis your database model for a `source-agency` table makes sense, but it doesn't solve the user's workflow for selecting agencies in a convenient way. Maybe it doesn't have to, and this is just a front end problem.

This becomes two hops from a data source → its geographic jurisdiction, which is how we search. Already, it's a little weird the way we associate data sources with agencies as a way to infer jurisdiction—the model I described above would mean aggregated sources (maybe all sources) directly describe _geographic jurisdiction_ which is sometimes inferred from associated agencies and sometimes added directly (in the case of aggregated sources).

Submission workflow:

- select an agency
   - geography is inferred
- if it's an aggregated source
   - select a geography and agencies are inferred
      OR
   - select an agency and geography is inferred

↑ in any case, we end up with a bunch of `source-agency` rows, which can be used in searches.

Search workflow:

- search by geography
   - see relevant sources, front-end logic for grouping 
- search by agency
   - see relevant sources
   - see related sources from agencies in the same geography

↑ the searcher doesn't care which db properties make sources show up

since `source` `agency` and `geo` are a related trifecta for search, `geo` data may want to be normalized in that table.

**Comment by maxachis** [comment]
Putting `geo` in the `source-agency` row will likely lead to duplicate information, since the geo will always be the same for the agency. But I do think separating `geo` from `Agencies` is likely a good idea; we'll just need to take into account the different forms of `geo`.

## Proposed Database Structure

An alternative solution is to further break up tables:
1.	Set up tables for Municipalities, Counties, and States (with municipalities and counties having a foreign key listing the county and state, respectively, they are a part of). This is similar to what I suggested before, but now they’re all in separate tables, rather than a single big table. 
2.	Set up linking tables for Agency_Municipalities, Agency_Counties, Agency_States
3.	Geographic information for each agency is moved from `Agencies` to these linking tables. The agencies retain `jurisdiction_type` column. Critically, each linking table will only contain links to agencies of the relevant jurisdiction type (i.e., “county” In Agency_Counties, “state” in Agency_States, “municipal”, “local”, and “school” in Agency_Municipalities). 

## The Front-End Experience

The front-end experience for submitting can be the same – it’s just that a unified submission will be broken down into its constituent links upon completion. This also reduces duplicate information and hence the risk of data integrity issues – county-level agencies will have their state inferred, as well as all relevant municipalities, for one example:

The search experience should be a bit more logical, which I can illustrate with a few examples:

1.	Search for agencies ‘Allegheny County’: Retrieve all county-level agencies, as well as all municipal and local agencies in municipalities that are associated with Allegheny county. Then get all data sources associated with those agencies via `source-agency`.  
2.	Search for agencies across multiple counties. Chain together the same search as above, and eliminate duplicates in the results. 
3.	Search for National level agencies. Retrieve all agencies with jurisdiction type of ‘National’, and all data sources associated with them. 
5.	Search for ‘jail records’ in ‘Allegheny county’. This is probably where it’d get most complex. We’d get the agencies for Allegheny County and all municipalities, all `data_sources` rows mentioning jail records, and then return all of those data sources that are linked via `source-agency`to the agencies we describe.

## Conclusion 🦒

This is definitely a tough nut to crack, just because of how many different ways the various entities relate to each other, and how many different ways people can search for information. And I’m open to other alternatives. But this is the method that, at the moment, seems to me most capable of minimizing data, reducing risk of duplicates, and making logical relationships most clear.

**Comment by josh-chamberlain** [comment]
your description is certainly the most complete way to taxonomize jurisdiction, but I wonder about essentially creating a database of every city in the US and trying to keep that up to date. We can't be the only ones who would use such a thing, and I don't think we should build it from scratch.

Right now, our agencies table contains all the geo data, and it works fine for our needs except for sources which cover many agencies/places. I apologize if I'm being difficult, but I don't see how this new structure would change the way we handle aggregated agencies—I think the most useful idea in this thread so far is a table for `source-agency`, which I think we can have _without_ restructuring the way we link `agencies` and `geo`. Right?

**Comment by maxachis** [comment]
@josh-chamberlain I may be over-engineering a solution (wouldn't be the first time). If our agencies table currently works fine for our needs, then I'll withdraw those considerations -- why fix what ain't broke?

In that case, developing a `source-agency` table and integrating that into our workflow seems a sufficient solution to this conundrum. Would we want to make an issue for that?

**Comment by josh-chamberlain** [comment]
@maxachis OK, I made #272 and I think we can close this as a completed discussion

**Comment by maxachis** [comment]
@josh-chamberlain Agreed!
