### ISSUE TITLE
Users and login

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#24]
### Context

This is boilerplate login, reinventing zero wheels.

should be followed by #158

### Requirements

- [x] #4 
- [x] create a new login page for the app
  - https://data-sources.pdap.io/login
  - [x] `email` and `password` form fields, `Log in` button and `Create account` button
  - [x] upon successful login, show a page which says something like "You're logged in!"
  - [x] allow people to create a new user login, via simple form
  - [x] allow people to reset their password via email without admin intervention
- [x] by default users have the same permissions as the front end (public)

first permission will be given to admins, #163 

There's probably at least one existing library for this.

**Comment by josh-chamberlain** [comment]
@mbodeantor this is not next up, yet, but not too far off. Just passing to you for `refinement`

**Comment by mbodeantor** [comment]
The current login get user endpoint will need the api key functionality to be split out into a separate endpoint so that it returns a success or fail on match. We will also need to add a "role" column to the user table which this endpoint should also return. If the role is "admin" the front end should show the edit button. For now we can update the roles in the database manually.

In addition will need to add an update password endpoint for the reset password functionality.

**Comment by mbodeantor** [comment]
Backend work for this is finished: https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/196
