### ISSUE TITLE
v2: Allow github oauth

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#296]
### Context

part of https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/248

We're going to be integrating tightly with GitHub already for #256. It's way cleaner if we let people link their account.

#### Back end

- Support GitHub OAuth in our user and login model
     - [start by creating an oauth app here](https://github.com/settings/developers)
- [x] josh: transfer oauth app to PDAP org
- [x] allow people to sign up and login with github oauth
- [x] infer the account email address from github
- [x] add to the readme that `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` are required for github OAuth

#### Front end

- [ ] Add a `Sign up with GitHub` button on the signup page, with caption "(Recommended, if you already use GitHub. You can always link your account later. )" (fig 1)
- [ ] Add a `Log in with GitHub` button on the login page (fig 2)
- [ ] If people try to log in via email after signing up with GitHub, they will need to set a password. We can use a modified version of the password reset page. (fig 3) They should be prompted to do so (and redirected to login)

#### Meta

- [x] Acknowledge and resolve discussion about GitHub Access Tokens and security risk

I used Balsamiq to make these wireframes, so they are for placement and flow only. We should just use our styles

### Fig 1
<img width="736" alt="Screen Shot 2024-10-30 at 3 05 35 PM" src="https://github.com/user-attachments/assets/2e153dd8-596a-4351-8802-c44a97936721">

### Fig 2
<img width="927" alt="Screen Shot 2024-10-30 at 3 26 47 PM" src="https://github.com/user-attachments/assets/11a5e0a5-d17d-4a70-a484-d9efa028cebd">

### Fig 3
<img width="926" alt="Screen Shot 2024-10-30 at 3 29 01 PM" src="https://github.com/user-attachments/assets/736ee62a-54ff-4b9f-a327-bd9cd6a635b6">

**Comment by maxachis** [comment]
@josh-chamberlain Would we want to store any of their Github user information on the backend, or (in line with you wanting to minimize personal data in our databases), not?

**Comment by maxachis** [comment]
@josh-chamberlain Additionally, would this obviate the user tokens logic, which you previously said might end up being replaced at some point soon?

**Comment by josh-chamberlain** [comment]
@maxachis unclear how I missed these comments! Sorry.

By GitHub user information, do you mean anything beyond username? I don't think so.

Ideally, people would be able to log in via email as well as github auth.

**Comment by maxachis** [comment]
@josh-chamberlain This issue currently only mentions frontend components -- should we consider this issue to also include backend components, or would that be defined in a separate issue?

**Comment by maxachis** [comment]
@josh-chamberlain The first step is to register with the OAuth service -- in this case, GitHub. 

Per [this tutorial](https://www.oauth.com/oauth2-servers/accessing-data/create-an-application/), this would be done by accessing https://github.com/settings/developers and clicking “New OAuth App”. We may need to create two applications here, one for development and one for production, as only one authorization callback URL is permitted. For now, we can just create a development app.

The authorization callback URL must be an HTTPS endpoint, which means we may need to first develop that. I'm guessing it would be called `/auth`. I _think_ that would mean, in the case of dev, `https://data-sources-v2.pdap.dev/api/auth`. Again, bearing in mind that we haven't developed that endpoint yet.

**Comment by maxachis** [comment]
# Implementation Notes

I talked with ChatGPT to get a handle on Oauth [here](https://chatgpt.com/share/d2a2b630-f0be-4836-bac8-bbc6b846c0ae). Because it's ChatGPT, I'll need to cross-reference with less hallucinatory sources, but by my understanding:
1. We use one endpoint to direct users to the Oauth server
2. We use another for registering callbacks, where we store the Oauth access token and send the user the session id, which the client stores as a secure cookie (or we can store some of that information server-side).
3. When the user makes requests on protected endpoints, we check that they're logged in, and use their provided session information to find the associated user permissions, and use that to determine their access to particular resources.

**Comment by maxachis** [comment]
# Resources
These are resources I've been using in order to figure out how the heck to put everything together:

* https://blog.miguelgrinberg.com/post/oauth-authentication-with-flask-in-2023 
* [My conversation with ChatGPT](https://chatgpt.com/share/d2a2b630-f0be-4836-bac8-bbc6b846c0ae). I've tried to avoid using any of its code directly and instead using it to prototype and make sure I'm getting a handle on the basics.

**Comment by josh-chamberlain** [comment]
OAuth app created! `Device flow` has been enabled, though I wasn't sure that was necessary.

**Comment by maxachis** [comment]
# Testing OAuth Locally

![image](https://github.com/user-attachments/assets/7b0f77a1-73c6-4808-9803-e1d11ffe4ee4)

![image](https://github.com/user-attachments/assets/eafbf0cf-ebe4-43d4-a798-3f158e70e1e8)

**Comment by maxachis** [comment]
Success! Got my first response.json:

```json
{'login': 'maxachis', 'id': 48846180, 'node_id': 'MDQ6VXNlcjQ4ODQ2MTgw', 'avatar_url': 'https://avatars.githubusercontent.com/u/48846180?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maxachis', 'html_url': 'https://github.com/maxachis', 'followers_url': 'https://api.github.com/users/maxachis/followers', 'following_url': 'https://api.github.com/users/maxachis/following{/other_user}', 'gists_url': 'https://api.github.com/users/maxachis/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maxachis/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maxachis/subscriptions', 'organizations_url': 'https://api.github.com/users/maxachis/orgs', 'repos_url': 'https://api.github.com/users/maxachis/repos', 'events_url': 'https://api.github.com/users/maxachis/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maxachis/received_events', 'type': 'User', 'site_admin': False, 'name': 'Max Chis', 'company': None, 'blog': '', 'location': None, 'email': None, 'hireable': None, 'bio': None, 'twitter_username': None, 'public_repos': 31, 'public_gists': 0, 'followers': 4, 'following': 5, 'created_at': '2019-03-23T00:43:43Z', 'updated_at': '2024-06-14T14:21:26Z'}
```

**Comment by maxachis** [comment]
With the hardest part done, now it's just a matter of implementation and how to tie everything together. Current outstanding questions/issues/todos:

- [ ] Per [this Stack Overflow](https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope): To get a user's Github email, I'll need to make an additional request, using the access token received. So I need to develop that. 
- [ ] I'll need to add logic for when a user is already logged in. 
- [ ] If a user can both create an account using their Github login and also link an account that already exists using an email, I'll need either separate endpoints or separate logical flows for that.
- [ ] How to use this to navigate endpoints requiring authorization is still an open question. Probably the easiest way is to continue to use our `/login` endpoint and/or add a `/login-with-github` endpoint, both of which can provide an API access token. 
- [ ] I'll need to develop tests for this. Because part of it interfaces with a third party, Even the integration tests will need to have some components mocked.

**Comment by maxachis** [comment]
@josh-chamberlain In the description for this issue, you indicate we want to use OAuth for logging in via and linking the account to a Github Account. Do we also want to use it to enable people to *sign up* using their Github Account?

This would add some additional logic -- for example, if they sign up using Github, do we still need them to set a password? -- but it would also enable a one-click sign-up in addition to one-click login.

**Comment by josh-chamberlain** [comment]
@maxachis 

- yes, people should be able to sign up with a github account. This is a good point.
- #274, the user profile, contains the API key

**Comment by maxachis** [comment]
>  allow people to update their email address

Would it be alright if we made this requirement a separate issue? Partly because this is already a dense issue, and partly because I think it's a bit more general than OAuth logic. Presumably a person could update their email address outside of the OAuth logic as well.

**Comment by josh-chamberlain** [comment]
@maxachis matter of fact, I'll delete it—not everything needs to be self serve for the MVP.

**Comment by josh-chamberlain** [comment]
@joshuagraber I think this one's ready for the front end now that https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/pull/62 is in dev!

**Comment by maxachis** [comment]
# Expiration Tokens and Security Risk

@josh-chamberlain After talking with @joshuagraber about this, we've settled on an implementation that works, but has a security hole, although not the most substantial one.

To make a long story short: To keep things modular and workable within OAuth's wonky constraints, we have it so that, after calling the OAuth endpoint, the user is redirected to a new page with the GitHub Access Token provided as a query parameter in the URL. The client then detects the presence of this query parameter and uses that to perform OAuth actions -- in this case, either logging in the user, creating a user with their GitHub information, or linking their GitHub account to the user's PDAP account.

The main problem here is that the GitHub Access Token has an _unmodifiable_ expiration time of eight hours. So a gremlin could pick up that query parameter and use it.

Of course, that access token is very limited in its scope -- it can provide basic public user information, and the user's emails, and that's it. The bigger risk is that someone could use it to log into a PDAP account and make merry with it. 

There are alternatives we could use to circumvent this. So far, we decided it was sufficient for us to just work on getting the overall implementation done, rather than try to navigate this. But we do leave it up to you what you think makes sense.

#### Alternatives
1. Revoke Access Token immediately after use -- if a user wants to login/create/link via GitHub again, they'll need to authorize every time. 
2. Provide a JWT in the query (whose expiration we can set) which translates into the access token client-side but which doesn't actually provide the access token
3. Some other options I'm not thinking of right now

**Comment by josh-chamberlain** [comment]
@maxachis thanks for laying it out for me. I think alternative 1 sounds not-good, but alternative 2 with expiration of, say, 5 minutes sounds good and standard. 

Yes, I think doing this as a future enhancement is OK! I'd say we might as well get it done as part of v2, though, as it doesn't seem too involved.

**Comment by maxachis** [comment]
@josh-chamberlain Sounds good, and I have now addressed this!

#515
