### ISSUE TITLE
v1 quicksearch string matching bug

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#346]
### Context

flagging this partly because it went unnoticed for so long—we should make sure we are not replicating things like this with new search: #249 

### Description

This is related to unexpected/missing search results in ways I don't quite understand.

#### Search 1: `dashboard` in `allegheny county`
- https://data-sources.pdap.io/search/dashboard/allegheny%20county
- 1 result: `Allegheny County Bail Dashboard`

#### Search 2: `all` in `allegheny county jail`
- https://data-sources.pdap.io/search/all/allegheny%20county%20jail
- 13 results, one of which includes the word "dashboard": `Allegheny County Jail interactive population dashboard`, which should have shown up in search 1

#### Search 3: `dashboard` in `allegheny county jail`
- https://data-sources.pdap.io/search/dashboard/allegheny%20county%20jail
- no results, should have included the result from search 2

### Requirements

- [x] diagnose the bug + identify possible steps to fix

**Comment by EvilDrPurple** [comment]
Can confirm this bug is still present in `dev` branch of v2 as well

**Comment by EvilDrPurple** [comment]
It seems the issue was with the `.title()` here:
```python
cursor.execute(QUICK_SEARCH_SQL.format(search.title(), location.title()))
```
The function capitalizes the start of every word, causing some searches to slip through the cracks since they are case sensitive. Removing them fixed the outlined searches. I'm going to make it so that the search terms and the database terms are lowercased to solve any case-sensitivity issues in searches. That is assuming there was no foreseeable reson for it to have been set up this way in the first place

**Comment by EvilDrPurple** [comment]
PRs submitted for both [v1](https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/347) and [v2](https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/pull/42)

**Comment by josh-chamberlain** [comment]
case sensitivity should never be a thing for these searches. thank you!
