### ISSUE TITLE
Data Source API Documentation

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-sources-app#35]
Add a page to Notion about how to authenticate with the API, endpoint available, and any parameters required to use the endpoint: https://www.notion.so/pdap/Developer-resources-7818b31a318f482ead6906c75cb24083

**Comment by kalenluciano** [comment]
Here's the Notion page for your review: https://www.notion.so/pdap/Data-Source-API-Documentation-6120fe451ac643d5aaf115694a47f27f

**Comment by mbodeantor** [comment]
Awesome! This is super thorough. I think it just needs a section about the quick-search endpoint and it is good to go!

**Comment by kalenluciano** [comment]
@mbodeantor I added a quick-search endpoint section. Let me know what you think. 

I was also wondering if you think we should add separate pages for each endpoint. It's manageable now, but as we add more to it, it might be overwhelming all on one page.

**Comment by josh-chamberlain** [comment]
Let's also be sure to link to the API docs from `data-sources-app/README.md` and link to this repository from the Introduction page of the API docs

**Comment by kalenluciano** [comment]
@josh-chamberlain @mbodeantor here's what I updated and what I need feedback on:
- I went through the API docs on GitBook and added in descriptions, parameters/body parameters, and responses. Please take a look and let me know what you think.
- I left a few questions on the old [Notion documentation](https://www.notion.so/pdap/Data-Source-API-Documentation-6120fe451ac643d5aaf115694a47f27f?d=806d932a8dc54b29acc8d54c07c59f19#fcb14f7de9c74b149f3f3186bf8b9025) to figure out whether/where to add some of the details about the parameters. I crossed out all the sections that we already transferred over to GitBook.
- I also left a few comments in [GitBook](https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/413/api/endpoints/~/comments) for your review.
- Lastly, I added a link to the PDAP documentation in the ReadMe. Currently, the link is pointing to [here](https://docs.pdap.io/) since the API docs aren't published yet. I can change this once we finalize and publish the docs

**Comment by josh-chamberlain** [comment]
@kalenluciano gitbook looks good to me, waiting to merge until things are resolved. say the word if you need someone to mash that

**Comment by kalenluciano** [comment]
Perfect! I just resolved Marty's comments, too. He suggested moving the login and sign up endpoints to the admin page. They basically said the same thing in different formats and only PDAP staff are managing users right now. 

It looks like Marty is about to finish deploying the backend to Digital Ocean, so I'm going to wait until he does that before publishing these docs so that I can add in the BASE_URL. 

I'm also going to look into how to format the schemas in the responses section. It's fine the way it is, but it looks like there's a preferred syntax that I couldn't find yet.

**Comment by kalenluciano** [comment]
@mbodeantor this PR is good for your review now. I updated the link in the ReadME to point to the API docs

**Comment by mbodeantor** [comment]
Gitbook edits are merged!
