### ISSUE TITLE
Add `withdrawn` logic for `data_requests` and remove `volunteers_can_contact_requestor`

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#411]
### Context

* In Airtable, we had a check to indicate whether a data request was withdrawn.
* Now, we still want users to be able to withdraw a data request 
* However, we (presumably) don't want users to be able to modify the `Request Status` column in `data_requests` (which indicates a multitude of other statuses we want to be able to control and not have the owner modify)
* Additionally, remove `volunteers_can_contact_requestor`, which is _no more_!

### Requirements

* Remove `volunteers_can_contact_requestor` (so that it is _no more_)
* Create a `/data-requests/withdraw/{id}` endpoint, which will update the status of a request to `withdrawn` (and which will permit only the owner or an admin to update it).

### Tests

* Validate that `volunteers_can_contact_requestor` is _no more_.
* Test that new endpoint functions as expected.

### Docs

* Add documentation for new endpoint 

### Open questions

* None!

**Comment by josh-chamberlain** [comment]
ah, so users shouldn't be able to modify the status directly—but I would love to get this done without adding a property. I think there are ways to do it without adding a new property + still keeping the API CRUDlike / not adding an endpoint: https://chatgpt.com/share/f7093f06-94f6-4f3a-9987-97636cde57e9

and, remember: chat GPT is _never wrong._ 😈

Anyway, I'm sure there are plenty of other ways to do this so I'm not _too_ picky about it. I think this will be a common theme, though—lots of actions could potentially impact an item's status.

**Comment by maxachis** [comment]
@josh-chamberlain 

After much thought and prayer over it, I can see some ways to do it while keeping it, er, CRUD-ish:
1. We can have the request status be modifiable only in this specific situation. We'll need to check on any updates whether request status is specified as one of the columns to modify, and whether the modification by the owner is to `Request withdrawn` (which they'll need to spell correctly).
2. We add a `withdrawn` parameter to the endpoint itself, which if true will ignore all other functionality and set it to `Request withdrawn`. Simpler for the user to do, and simpler logic for us, but definitely makes it less CRUDy
3. The PATCH method, which I've never used but is an option (and one I'd have to explore further).

What do you think?

**Comment by josh-chamberlain** [comment]
@maxachis hmm, I like the second option. In the UI, this would be on a straightforward path: the appropriate users could see a "withdraw request" button, and clicking it would hit the endpoint correctly (spelled right, checking permissions). 

Even for API users—I see an UPDATE endpoint which accepts a `status` property. I make API calls to try to modify the status, and the app deals with me as it sees fit, sending a "you don't have permissions" message if necessary. We also have a wee table in the docs which might lead me to expect I cannot update the status. We could choose to make this reversible. It has the advantage of being a standard API design, which is user-friendly.

This is conceptually much simpler, and feels more like building a structure with 2x2 lego bricks rather than those super-special + unique pieces that aren't as transferable to other use cases. No matter what, we have to check to see if the user has the appropriate permissions—so we might as well structure things in a basic way.

**Comment by maxachis** [comment]
> @maxachis After doing some soul-searching of my own, I think it's OK to have a whole endpoint with the specific function of updating a specific property, which hopefully makes permissions simpler. We shouldn't need to do too much of this, and can have broader endpoints for editing broader ranges of properties, but I think an endpoint called "withdraw-request" in the "requests" namespace is user-friendly and makes perfect sense! I was overthinking it before.

Got it! Issue is updated!
