### ISSUE TITLE
Requests approval workflow

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#422]
Part of https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/299
Part of #32 
Related to #163 

### Context

We need a view that allows admins to `edit` some properties and `approve` incoming requests; this should probably have a dedicated endpoint.

We could do the front end in retool.

#### Back end

- [x] requests start with `intake` status, and the approval process either causes them to be `archived` (the approver should be prompted to enter an `archive_reason`, like with data sources approval) or `ready to start`
   - after this, we should infer the status from github: #299 
- [x] endpoint for admins to edit requests

#### Front end
- [ ] retool workflow for selecting and approving requests

### Tests

- TBD 

### Docs

- TBD

### Open questions

- TBD

**Comment by maxachis** [comment]
@josh-chamberlain Thanks to my efforts with data requests in general, I _believe_ we actually have the backend portion for this addressed via the changes in #390. What do you think?

**Comment by josh-chamberlain** [comment]
@maxachis yes, I think the API is ready! or, close enough to ready at this point that it's hard to tell otherwise unless we try : )

**Comment by maxachis** [comment]
@josh-chamberlain Here's a draft version for your perusal! 

https://pdapinternal.retool.com/apps/033f3aea-7ac3-11ef-8e85-5b7af40d9169/Data%20Requests%20Internal

**Comment by josh-chamberlain** [comment]
@maxachis looking good! I think a few changes are in order:

- we're only going to need requests with a status of `Intake`...but can we do that filtering in retool? In any case, we will need to filter on status for other displays of requests (routinely hiding archived/intake ones)
- could you make this have the same 3-button interface as the data sources approval, adding one to create a test? Except I think the actions should be above the form.
- can remove `github_issue_url` from this display (especially since it won't exist yet)
- can remove `pdap_response` from this display (too early)
- can remove `record_types_required` from this display (not in the submission form; questionably useful)
- can remove `request_status` from this display (that will happen as a result of the action taken with the buttons)

**Comment by maxachis** [comment]
> * we're only going to need requests with a status of `Intake`...but can we do that filtering in retool? In any case, we will need to filter on status for other displays of requests (routinely hiding archived/intake ones)

We can _technically_ do that filtering in retool, but I think it makes more sense to filter it in the `GET` request (and to add a means in the API to perform that filtering, similar to how with `/data-sources` we can currently filter based on approval status). My reason for not filtering in retool is that:
1. We'd be applying that filtering after already retrieving all that data in a comparatively more expensive query, as opposed to just getting less data in the first place
2. Because the data is paginated, we'd only be receiving a subset of the data at a time, which may not be guaranteed to have data with the request status we are looking for

> * could you make this have the same 3-button interface as the data sources approval, adding one to create a test? Except I think the actions should be above the form.

I can do that, but I do need to check what the 2 non-test buttons should do? I'm guessing they should be `Approve` and `Reject`, but what states does the request become after this?
* `Approve` -> `Ready to start`?
* `Reject` -> `Archived`? Or create a new status of `Rejected`, to differentiate from `Archived`?

> * can remove `github_issue_url` from this display (especially since it won't exist yet)

Done!

> * can remove `pdap_response` from this display (too early)

Done!

> * can remove `record_types_required` from this display (not in the submission form; questionably useful)

Done!

> * can remove `request_status` from this display (that will happen as a result of the action taken with the buttons)

Will do once I get the answer to the above Approve/Reject question?

**Comment by josh-chamberlain** [comment]
@maxachis I think `Archived` is plenty, with an `Archive reason`. These aren't really `rejected` in the same way as sources. I edited the issue body.

When you `Archive`, you are prompted to enter an `Archive reason`.

**Comment by josh-chamberlain** [comment]
merging with https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/74
