### ISSUE TITLE
v2: Endpoint for getting requests related to a source (and vice versa)

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#432]
### Context

Part of #248 
Part of #254 and #253 

### Requirements

- [ ] on `data source details`, we will need to get related requests
- [ ] on `request details`, we will need to get related sources

There should be endpoints for these, using the `data sources-requests` link table.

### Tests

TBD

### Docs

API docs

**Comment by maxachis** [comment]
@josh-chamberlain 

## Structuring the endpoint
The simplest way to do this from an implementation standpoint is to create a `/data-sources/id/{id}/related-requests` and `/data-requests/id/{id}/related-sources` endpoint (piggybacking off the existing `/data-sources/id/{id}` etc. endpoints). I do note, however, that this assumes that users will only want to get the related requests/sources for one source/request at a time. I think that's a reasonable assumption when we're still early in development and we don't fully know our user's preferred use cases, but it is worth making that assumption explicit.

Alternatively, if we were interested in getting multiple related sources/requests for multiple sources/requests at a time, we could instead: 
1.  Add related sources/requests to the request/source results already returned, 
2. Also create `/data-requests/page/{page_number}/related-sources` etc. endpoints

1 would violate the standard I discuss [here](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/429#issuecomment-2319558335), where I recommend keeping the basic endpoints limited to one table each. I still stand by that for the moment, in part because it helps separate logic and keep things simpler for us and the end users, even if it's more redundant for some use cases. 
2 feels like overkill at this juncture.

## What are we returning?
Assuming we're going with the "by-id" form, it then is worth asking what information do we want returned for each related request/source. It could be:
1. A simple list of IDs of the related requests/sources.
2. IDs along with a limited suite of additional information on the requests/sources derived from their relevant tables (e.g., `name`, `submission_notes`, etc.)
3. The full suite of allowable columns for each result, just as if we were querying the `/data-requests` or `/data-sources` endpoint through that endpoint.

I'm guessing we don't want 3, because that makes things a bit _too_ redundant. I could see either 1 or 2 as sensible, though. 

## No ownership permissions to take into account
I'm also making an assumption that we'll ignore ownership permissions in the case of all things data requests; whatever the results are, it won't matter if the user owns any of the related requests (if they are querying `/data-sources/id/{id}/related-requests`) or if the user owns the request they are seeking the related data sources of (if they are querying `/data-requests/id/{id}/related-sources`).

## Adding/Removing related sources/requests.

Presumably, if we're returning related sources/requests, we also want the option to add or remove them. Again, I'm assuming we only want to add or remove one related request/source at a time.

I'm seeing two options:

1. `POST`/`DELETE` on `/data-sources/id/{data_source_id}/related-requests/{request_id}`
2. `PUT` on `/data-sources/id/{data_source_id}/related-requests`, with the request ID and action in the body

I can't say I have a strong preference, but I probably favor 1, just because it's more RESTful, even if it means an extra endpoint.

**Comment by maxachis** [comment]
# Test Cases/Design Assumptions

In this case (pun not intended), I'll structure the tests based on a set of design assumptions which I'll provide below:

1. Users should not be able to add a related request/source already added to that source/request; attempting to do so will either trigger an error or an alert that the request/source was already added.
2. Users should not be able to delete a request/source that does not currently exist for that source/request; attempting to do so will either trigger an error or an alert that the request/source does not currently exist.
3. Users must have a specific permission (`DB_WRITE` or something else we specify) to add/delete a related request/source.
4. When requesting related requests/sources for a given source/request, results will be structured as a list provided in the `data` key of the json request body.
5. If there are not related requests/sources for a given source/request, a message "No related requests/sources found" should be provided in lieu of a list.
6. Each call for a related request/source for a given source/request should return ONLY request/sources for that source/request identified as related, and not return any others.

**Comment by maxachis** [comment]
> Interesting, I had always used this in Airtable by starting from a request and adding/removing related data sources. Does the direction matter, really? I think the endpoint would be usable either way, because you have both the source and the request at hand. But if there's no obstacle to it, I think it makes more sense to interact with /requests/id/related-sources/{source_id}. This is marginal.

Alright! We can have the interaction only occur from the data sources side (which should simplify things). So owners and admin-level permissions people can add/remove related data sources for their requests.

**Comment by maxachis** [comment]
@joshuagraber Including Joshua in this as a sanity check to make sure we're thinking through this right.

**Comment by joshuagraber** [comment]
> Related to the conclusions drawn in https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/429#issuecomment-2338212545, perhaps it is useful to have the associated data sources included in the basic /data-requests GET function. It would follow a structure similar to the results there, with a list of the associated data requests included as a property of the main data requests JSON entry being returned.

Yes, I think this would be useful.
