### ISSUE TITLE
v2: duplicate URL checker endpoint

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#434]
### Context

We're building a "new data source" workflow in #252. When people are still _in the form_, and they have pasted a URL, we want to check to see if it's a duplicate in the background, and catch it before they try to submit.

### Requirements

- [ ] this endpoint should accept a `url` and check our database for duplicates, including URLs which have not been approved
- [ ] it should return any matching (duplicate) `urls` with their `approval_status` and `rejection_note`
- [ ] ideally, it should find _near-duplicates_ (things like a trailing `/` at the end, http/www permutations within reason)

### Tests

TBD

### Docs

API docs

**Comment by maxachis** [comment]
@josh-chamberlain It is worth noting that we already have some duplicate source_urls in our database right now! Specifically, we have:

* 94 urls that occur in two data sources
* 8 urls that occur in three data sources
* 4 urls that occur in four sources
* 2 urls that occur in five data sources
* 1 url that occurs in six data sources


Do we want to do anything about these right now? Does this impact our design?

**Comment by maxachis** [comment]
A few other points worth noting; maybe not for this issue, but for others

## URL Fragments

Occasionally, URLs contain a URL fragment (the "#some-content" section you see at the end of a url). These typically denote a specific position on a page or otherwise organize a sub-page. Some examples we have in the database include:
 
1. `phillypolice.com/accountability/findings/#!#%2F_ga=2.88868763.1007266185.1596139754-12687582.1596139754`, which seems to limit it to a specific search
2. `https://www.muckrock.com/foi/detroit-314/shotspotter-policies-140369/#file-1067485`, which directs to a specific location on the page (and is otherwise a duplicate with `muckrock.com/foi/detroit-314/shotspotter-policies-140369/#files`)
3. `https://directives.chicagopolice.org/#search`, which directs to a specific tab on a web page.
4. `https://docs.google.com/spreadsheets/u/0/d/10tDQ5t7QHiOTw4eEZVCMkGvh5II0bSiHqGzioyfKUsc/htmlview#`, which doesn't seem to impact the web page at all. 
5. `https://www.sjpd.org/records/crime-stats-maps/force-analysis-data#:~:text=The%20San%20Jose%20Police%20Department,on%20our%20public%20web%20site.&text=For%20additional%20information%2C%20please%20contact,at%20408%2D277%2D5200.`, where the fragment seems to be a remnant from a Google  search but which also doesn't direct to anything on the page.

These will further muddy the waters as far as duplicates go. Fortunately, in our current database, we only have about 33 where this is the case, but it's something worth taking into accont.

I could see us addressing that in a few ways:
1. Forbidding URLs which have a url fragment in them
2. Accepting them but removing everything after the url fragment (maybe with a check to make sure it's still valid). 
3. Giving some sort of warning to users who submit urls with url fragments that they make it more difficult for us to organize/deduplicate and so could they pretty please remove it.

## Google Docs Links

We sometimes have a link to Google Docs, which run into one of two issues:
1. As in `docs.google.com/spreadsheets/d/1k-SBpcA0Qc0znWFYKu4JtqNfnFFNPf7Rhl6mT_bPjvU/edit#gid=0`, we may need access to view it, which defeats the whole purpose of it in terms of transparency.
4. As in `https://docs.google.com/spreadsheets/d/151J17PmQualbo7ONsLtei6I0jE_6C5Ut/edit?gid=264210893#gid=264210893`, it's a lot of information, but there's not a trail of sources we can use. Whether it's a leak or just something someone did, it's a bit harder to validate it when it's not attached to anything specific.

**Comment by maxachis** [comment]
Current plan is, as usual, creating a materialized view to make responses quicker

## Materialized View Design

```sql
CREATE MATERIALIZED_VIEW IF NOT EXISTS public.distinct_source_urls
TABLESPACE pg_default
AS
	SELECT DISTINCT 
		-- Remove trailing '/'
		RTRIM(
			-- Remove beginning https://, http://, and www.
			LTRIM(
				LTRIM(
					LTRIM(
						SOURCE_URL, 'https://'),
					'http://'
				),
				'www.'
			),
			'/'
		)
	FROM data_sources
	WHERE 
		source_url is not NULL
```

**Comment by josh-chamberlain** [comment]
@maxachis 

### Existing duplicates

Hmm, I wonder how many of these have already been un-approved? Anyway, I can deal with them in Airtable for now. There's a nifty extension, and I will add it as a nice-to-have on #32 

### URL fragments

This one is annoying, because many of them look like they should just be named anchors but actually cause a page load and go somewhere else. At most, we should give a warning, but there's not much else we should go out of our way to do I don't think.

### Google docs links

Yeah, these are not ideal sources. As with any link, people would ideally make sure it works `incognito` before they send it to us. I rejected that one, as we had a better source for it anyway. That second one for non-haz citations is questionably useful, but I would argue not because it's a google doc. Links to random spreadsheets without context come in all shapes and sizes. That's why we have our database to provide context!

**Comment by maxachis** [comment]
@josh-chamberlain One implementation detail I'd like your feedback on.

Using the power of Marshmallow Schemas, I'm able to ensure that URLs passed to this can check to see if the URLs provided are valid as well as whether they're duplicates. However, Marshmallow's url checking is quite strict -- it won't permit something that doesn't begin with a valid url schema, like `https` or `http`. So something like `www.example.com` would not be considered valid, but `https://www.example.com` would be. 

Do we want to have that level of strictness (and do we want to have that in this endpoint)?

**Comment by maxachis** [comment]
@joshuagraber For you, does this response format make sense?

```json
{
  "duplicates": [
    "original_url": "https://www.example.com",
    "rejection_note: "Sample rejection note",
    "approval_status": "Rejected"
  ]
}
```

And related to the question I posed to @josh-chamberlain: What do you think makes sense in terms of url validation? And if we want url validation in this endpoint, how would you want that delivered?

**Comment by josh-chamberlain** [comment]
hmm. Most browsers will load any old URL, trying https and then http. When we _add_ URLs to the database, or when we do URL sweeps for our various purposes, we could be checking for SSL and then prepending http/https as necessary. In the case of checking for duplicates, I think we should ignore `http://` and `https://`, i.e. whether or not those strings are different at the start of the URL, they should be considered a duplicate

Duplicates
`https://www.example.com`
`http://www.example.com`
`www.example.com`

**Comment by maxachis** [comment]
@josh-chamberlain Got it! Easy enough to fix. Just made a quick update to account for that.
