### ISSUE TITLE
Update `/data-requests` `GET` and add `/user/data-requests` endpoint

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#446]
### Context

* Currently, the `/data-requests` `GET` logic returns both data requests the user owns, and data requests the user doesn't own.
* The current format for the response is as follows:
```json
{
  "message": "string",
  "count": 0,
  "data": [
    {
      "column_1": "Value for first column",
      "column_2": "Value for second column",
      "column_etc": "And so on..."
    }
  ]
}
```
* Currently, balancing variable column permissions with the fact that a user is probably interested in their own data requests first makes the logic a little hinky: 
* Data requests the user owns are returned first, followed by all other data requests. In other words:

```json
{
  "name": "owner_made_data_request"
  "common_column": 123,
  "owner_only_column:" "val"
},
{
  "name": "non_owner_made_data_request"
  "common_column": 123
}

```

* The user's data requests have more columns than non-owned data requests, but they're both returned in the same array.
* Let's modify this to improve accessibility and flow.

### Requirements

- [ ]  Modify the existing `/data-requests` `GET-MANY` and `GET-BY-ID` endpoints to only return column permissions that vary between Standard API users and Admin users
- [ ] Create a separate `/user/data-requests` endpoint which uses the JWT of the user to return all data requests which that user has created and owns. 
- [ ] All other other `/data-requests` endpoints have their logic unchanged.  

### Tests

* Add tests for the new endpoint, and modify the existing tests for the previous endpoint to account for the shift in logic.
* Include schema tests to ensure the endpoints behave as expected when expected (or unexpected) data is passed to them. 

### Docs

* Documentation will need updated if endpoint logic is updated.

### Open questions

* TBD

**Comment by josh-chamberlain** [comment]
Hey, this is a good question! Here is a big picture response that does not address implementation details:

1. Side note terminology-wise, I think we decided "creator" is more accurate than "owner"
2. In most cases, we would want to treat all requests the same, regardless of who created them. I don't think we need to assume that a user wants to see their own requests first, at least not as the default, and when a user is looking at a search results page, that is probably not the time to show hidden fields anyway.
3. In some circumstances (i.e. the "my requests" section of #274), we _would_ want to show users their requests, and that is _also_ the time we would want to show hidden properties. So, I think it is OK to expect that we would only get the additional "I created this" properties and order of response if they were specifically requested, either via a separate endpoint or parameter (someone else should decide the technical details).

If we do it this way, we can decide on the front end whether to show a user's own requests first. I think this is a more flexible solution that will require fewer back end changes over time due to the whims of, uh, product leaders. I may be contradicting my past self here.

**Comment by joshuagraber** [comment]
> I don't think we need to assume that a user wants to see their own requests first, at least not as the default, and when a user is looking at a search results page, that is probably not the time to show hidden fields anyway.

Agreed. And I can anticipate performance concerns if there turn out to be a lot of requests around some locations.

> In some circumstances (i.e. the "my requests" section of https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/274), we would want to show users their requests, and that is also the time we would want to show hidden properties. So, I think it is OK to expect that we would only get the additional "I created this" properties and order of response if they were specifically requested, either via a separate endpoint or parameter (someone else should decide the technical details).

Also agreed. Something like `/data-requests?user={user_id}` or `/data-requests/user/{user_id}` could work, in combination with reading the auth token passed and determining whether it is associated with the same user id which is passed as route/query param. Wyt about that @maxachis?

**Comment by maxachis** [comment]
@josh-chamberlain @joshuagraber Of the two options which @joshuagraber provided, `/data-requests?user={user_id}` would be the least intrusive to the existing endpoint design, and would align with the schema of having filter parameters for the `GET-MANY` endpoints. 

My main point of pause is how this would be communicated to the end user. If I'm understanding it correctly:
* The unfiltered endpoint would return a simple list of data requests, all with the same columns
* The filtered endpoint would return the data requests only for a single user, and if that single user is the same as the requestor, it includes additional hidden columns.
* In addition to this, admins may be able to see additional columns more than the creator might. 

While I think allowing the filtering of queries by which user created it makes sense and can be included in the above endpoint, I do wonder if the hidden fields should nonetheless be displayed only in a separate endpoint, such as one the following:  `/user/data-requests`, which returns the data requests for the user based on their provided auth info, with nothing specified in the endpoint address.
This makes more concrete the difference in access and enables us to begin creating a series of endpoints which could be used in a user profile.

**Comment by joshuagraber** [comment]
Good point @maxachis, it does seem simpler and cleaner to have this live in the users namespace.

**Comment by josh-chamberlain** [comment]
@maxachis thirded! One public, unfiltered endpoint, and one in the users namespace. Makes much sense!
