### ISSUE TITLE
Retool: Source and Request Intake

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-sources-app#74]
### Context

We would like to replace Airtable for editing data sources and other information: part of https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/32

https://retool.com/

### Requirements

- [x] Create a single retool app with one page for **Data Source Intake** and one page for **Data Request Intake**
   - there should be a button for logging in, which prompts users for their credentials
     - for the development period, this can just auto-use admin credentials
   - the structure of each intake workflow is:
     - a row of action buttons: `approve` `reject/archive` (source/request)
       - these buttons submit the status as well as changes made to the form as a PUT to the API
     - for the development period, an `add test row` button (for testing)
     - a form, prepopulated with the submitted properties and editable by the approver
- [x] We should use our API to make changes to the database, not edit the database directly
- [x] `requests` start with `intake` status, and the approval process either causes them to be `archived` (the approver should be prompted to enter an archive_reason) or `ready to start`
- [x] `sources` start with `intake` status, and the approval process either causes them to be `rejected` (prompt for a reason) or `approved`
- [x] after action is taken, everything should refresh

Nice to have:

- [x] since there are so many `data sources` properties, let's hide the empty ones and have a "show hidden properties" button to expand them

### Tests

We'll need to be careful about data integrity and which functions we allow.

### Docs

We'll need internal docs for approvers (how to access, when to do it)

**Comment by maxachis** [comment]
> PDAP has a Retool app/account initiated, I can share access when the time comes

@josh-chamberlain Can you share access with me?

**Comment by josh-chamberlain** [comment]
@maxachis invite sent. Marty's using retool as part of his `day job`, so the plan was that he would take this on / get it started so we have good patterns established

**Comment by maxachis** [comment]
@josh-chamberlain Surprise attack! I finished the app for the approval process!

https://pdapinternal.retool.com/apps/d4d34d3c-4755-11ee-b52a-c70af80341b4/Data%20Sources%20internal

**Comment by maxachis** [comment]
@josh-chamberlain A larger question is: What are all the distinct functionalities we want to perform with retool, in addition to the approval process?

**Comment by maxachis** [comment]
@josh-chamberlain there's also some issues in terms of using API calls rather than directly referencing the database, which I'll explain below:

1. Developing with the API will be more complex: the Retool interface works very well with a SQL database. In developing the above solution with the database alone, it didn't take me long to figure out how to design the database interactions to behave as desired. It's a UU how long it would take to develop stuff using the API, and development might be slower overall. 
2. API calls will probably be slower. In designing the approval workflow above, I created SQL queries that targeted only the operations we wanted it to perform (and were thus faster). Using API calls would involve more operational overhead and be slower, redirecting requests first to the Flask Client which would in turn redirect commands to the database.
3. Authentication poses some issues -- our `Bearer` JWT tokens are designed to be managed live by the web app and to expire after a relatively short period of time (currently about 15 minutes). The REST API resource configuration expects either a static value, _OR_  the implementation of a multi-step custom authentication structure, which is a bit more complex to implement and which I haven't tried yet.

And to be clear, using direct SQL brings with it disadvantages as well:
1. Security, obviously. If someone gets access to our Retool account, they can do a lot. This can be mitigated by ensuring the Retool application accesses the database as a specific user with limited permissions, but it is not eliminated.
2. It couples the Retool logic to the Database. If we alter the Database structure, the retool functionality will need to change as well. By contrast, if we stick to interfacing solely through the API, we can more easily adjust the database logic without worrying if we're going to break something in the retool app. 
3. We'll be less able to audit or log changes to the database -- or rather, we'd need to set up a new logging system based within the database, rather than using the one we're already planning to implement with the API.

So as to how to approach it, I'm unsure. I think the database option will be quicker to implement and leave us with less surprises in development (and we can transition to the API later), but poses risks which the API option does not. If I had to choose, I'd want to do the SQL option now just because it allows for more rapid prototyping, and the risks are comparable to those we currently face using Airtable.

**Comment by josh-chamberlain** [comment]
@maxachis wow, surprise attack indeed! Is it PDAP's birthday? 

I tested the workflow and it seems to be working. Nicely done. I slightly modified your "what we want retool to do" comment. It's exclusively related to approvals, though the approval process is the appropriate time to do things like fixing typos. re: database vs. API, I must be firm here. You are lovingly crafting an API to protect us from the pitfalls of direct database manipulation. One motion, many actions!

That said, there's not really much endpoint logic to worry about—provided someone has the appropriate permissions to be approving stuff in Retool, all they're really doing is modifying a few fields in a given row. It's a PUT endpoint. At the moment, this is just admins, and probably just me.

One immediate change I can see: can we just do a `reject` and `approve` button, and if someone selects `reject` they are prompted for a reason? The most common case is `approval`, which currently takes two clicks.

**Comment by maxachis** [comment]
@josh-chamberlain Got it! I'm working on the Rest API version of it (easier than I thought it would be), and will be providing that here shortly.

One last question, and it is a minor one: Do you want the approval queue to refresh after every approve/reject, or refresh with a manual "Refresh" button (or both)?

**Comment by maxachis** [comment]
@josh-chamberlain Updated API version is up! See [here](https://pdapinternal.retool.com/apps/6e3f5704-7365-11ef-a7a0-2ff6a691f56d/Data%20Sources%20internal%20-%20Rest%20API%20Copy).

Note that this is running the API from https://data-sources-v2.pdap.dev/api . This means:
* We're running on the stage database
* There aren't currently any *real* pending data sources, so we'd need to either add some or change the status of some to pending to make it work (either is fine because the database will refresh daily).

**Comment by josh-chamberlain** [comment]
@maxachis I didn't see this comment before we spoke today, so thanks for repeating yourself! It doesn't need to refresh after each one. That might be nice in the future—if there are concurrent approvers working, or someone leaves their session open, things would get annoying fast.

As mentioned, I think a "create test data source" button would be good for testing this workflow.

**Comment by maxachis** [comment]
@josh-chamberlain I added a create test data source button! Because of the nature of retool, it might take a second for the data to update, and the page may need to be refreshed. 

What do you think the next steps should be?

**Comment by josh-chamberlain** [comment]
@maxachis I'm getting a `{"status":400,"message":"Not enough segments"}`

<img width="326" alt="Screen Shot 2024-09-25 at 2 35 03 PM" src="https://github.com/user-attachments/assets/870002d5-5197-4594-8bdd-df9ce1cf6f33">

**Comment by maxachis** [comment]
@josh-chamberlain It's possible that you may need to go into the `Edit App` view, click `Re-Auth` next to the resource, and then run it, but also the error I got prior to running it was different than your own. I'll need to look into it further, and perhaps make use of that "Log In to Admin API" thing.

**Comment by josh-chamberlain** [comment]
@maxachis this did work for me, after a try or two—not going to dwell on it. 

I think the next steps would be _merging these two approaches_ so that they work in basically the same way.

- Data Request Intake features a form which shows the relevant properties, which can be edited before action is taken by the reviewer. Data Source Intake should have the same.
   - given the large number of properties, perhaps we should hide properties which are empty
   - given the exceptions that might occur, it might be nice to have a "show hidden properties" button, if such things are possible
- Data Source Intake features a lovely set of 3 buttons—`approve`, `reject`, `add test`. Data Request Intake should have 3 similar buttons, except with `archive` instead of `reject`. 
- In either case, submitting the form triggers a PUT request to the API.

I think once both forms look + work basically the same, you can safely assign the issue to me and I will experiment with layout and instructions for approvers.

**Comment by maxachis** [comment]
@josh-chamberlain I _believe_ this is now ready for you to take the reins, unless there's something I'm missing!

**Comment by josh-chamberlain** [comment]
@maxachis magnificent! I think this is good to close for now, and we can always come along with enhancements. I'm sure as I use it, some will occur to me.
